#!/usr/bin/env bash
# Auto-trigger pipeline for the microstructure-estimator pre-registration.
#
# Idempotent: skips if the report has already been generated. Respects
# a .training_in_progress lock file across cron invocations. Checks the
# pre-fit gate (>= 4000 joinable trades) before touching anything.
#
# Output: docs/feat/microstructure-estimator-report.md (+ .json), auto-
# committed and pushed.
#
# Spec: docs/feat/microstructure-estimator.md @ commit d5466937.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

REPORT_MD="docs/feat/microstructure-estimator-report.md"
REPORT_JSON="docs/feat/microstructure-estimator-report.json"
FEATURES_CSV="quant_short_features.csv"
LOCK=".training_in_progress"
LOG="microstructure_pipeline.log"
MIN_JOINABLE_TRADES=4000

log() { echo "[$(date -Iseconds)] $*" | tee -a "$LOG"; }

# -- Idempotency --------------------------------------------------------
if [ -f "$REPORT_MD" ]; then
    log "report already exists at $REPORT_MD; skipping. Remove it to force a re-run."
    exit 0
fi

if [ -f "$LOCK" ]; then
    # Stale lock if older than 6h: assume crashed and clear.
    LOCK_AGE=$(( $(date +%s) - $(stat -c %Y "$LOCK") ))
    if [ "$LOCK_AGE" -gt 21600 ]; then
        log "stale lock (age ${LOCK_AGE}s); clearing"
        rm -f "$LOCK"
    else
        log "lock present (age ${LOCK_AGE}s); another run in progress, skipping"
        exit 0
    fi
fi

# -- DB URL resolution ----------------------------------------------------
if [ -z "${DATABASE_URL:-}" ]; then
    if [ -f .env ]; then
        # shellcheck disable=SC1091
        set -a; . .env; set +a
    fi
fi

# Container-internal hostname won't resolve from cron's shell; fall back
# to localhost which the compose file exposes.
if ! printf '%s' "${DATABASE_URL:-}" | grep -q 'localhost\|127\.0\.0\.1'; then
    DATABASE_URL="postgresql://polyagent:polyagent@localhost:5432/polyagent"
fi
export DATABASE_URL

# -- Python interpreter ---------------------------------------------------
if [ -x .venv/bin/python ]; then
    PY=".venv/bin/python"
else
    PY="python"
fi
log "using interpreter: $PY"

# -- Pre-fit gate check (done inside Python; no psql dependency) ----------
GATE_OUT=$("$PY" -m polyagent.services.quant.ml.pipeline --gate-check-only 2>>"$LOG" || true)
GATE_RC=$?
log "gate check: $GATE_OUT (rc=$GATE_RC)"
if [ "$GATE_RC" -eq 3 ]; then
    log "gate not met; waiting for more data."
    exit 0
fi
if [ "$GATE_RC" -ne 0 ]; then
    log "gate check failed unexpectedly (rc=$GATE_RC); aborting"
    exit "$GATE_RC"
fi

# -- Lock and run ---------------------------------------------------------
touch "$LOCK"
trap 'rm -f "$LOCK"' EXIT

log "gate met; running pipeline"

"$PY" -m polyagent.services.quant.ml.pipeline \
    --features-out "$FEATURES_CSV" \
    --report-out "$REPORT_MD" \
    --report-json "$REPORT_JSON" \
    -v 2>&1 | tee -a "$LOG"
RC=${PIPESTATUS[0]}

if [ "$RC" -ne 0 ]; then
    log "pipeline failed with code $RC; not committing"
    exit "$RC"
fi

# -- Commit and push ------------------------------------------------------
if git diff --quiet --exit-code -- "$REPORT_MD" "$REPORT_JSON" 2>/dev/null \
   && ! git status --porcelain -- "$REPORT_MD" "$REPORT_JSON" | grep -q .; then
    log "no report changes to commit"
    exit 0
fi

DECISION=$(python3 -c "import json; print(json.load(open('$REPORT_JSON'))['decision'])" 2>/dev/null || echo UNKNOWN)
log "pipeline decision: $DECISION"

git add "$REPORT_MD" "$REPORT_JSON"
git commit -m "$(cat <<EOF
chore(microstructure): auto-generated training report ($DECISION)

Pre-registration: docs/feat/microstructure-estimator.md @ d5466937.
Generated by scripts/microstructure_pipeline.sh.

Co-Authored-By: Claude Opus 4.7 (1M context) <noreply@anthropic.com>
EOF
)"

# Push only if we have an upstream configured.
if git rev-parse --abbrev-ref --symbolic-full-name '@{u}' >/dev/null 2>&1; then
    git push 2>&1 | tee -a "$LOG"
fi

log "done"
